apiVersion: apps/v1
kind: Deployment
metadata:
  name: pis
  namespace: pis
  labels:
    app: pis
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pis
  strategy: {}
  template:
    metadata:
      labels:
        app: pis
    spec:
      containers:
        - name: pis
          image: quay.io/rhdevelopers/bgd:1.0.0
          env:
            - name: COLOR
              value: "blue"
          resources: {}

